
function calling() {
    try {
        callHook();
    } catch (error) {
        console.log('Error');
    } finally {
        console.log('');
        console.log('');
        console.log('');
        console.log('');
    }
}