function calling() {
    try {
        console.log('');
        console.log('');
        console.log('')
            .value;
    } catch (error) {

    }
}